# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from humans_msgs/HumanMarkerStamped.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import morse.middleware.ros.humans_msgs.msg
import std_msgs.msg

class HumanMarkerStamped(genpy.Message):
  _md5sum = "e4b954e663bdc578b9f1e5ff75a0b1c7"
  _type = "humans_msgs/HumanMarkerStamped"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header        header
HumanMarker   human

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data
# in a particular coordinate frame.
#
# sequence ID: consecutively increasing ID
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: humans_msgs/HumanMarker
uint64              id
bool                active
geometry_msgs/Pose  pose
geometry_msgs/Twist velocity

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation.
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space.
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','human']
  _slot_types = ['std_msgs/Header','humans_msgs/HumanMarker']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,human

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HumanMarkerStamped, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.human is None:
        self.human = morse.middleware.ros.humans_msgs.msg.HumanMarker()
    else:
      self.header = std_msgs.msg.Header()
      self.human = morse.middleware.ros.humans_msgs.msg.HumanMarker()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_QB13d().pack(_x.human.id, _x.human.active, _x.human.pose.position.x, _x.human.pose.position.y, _x.human.pose.position.z, _x.human.pose.orientation.x, _x.human.pose.orientation.y, _x.human.pose.orientation.z, _x.human.pose.orientation.w, _x.human.velocity.linear.x, _x.human.velocity.linear.y, _x.human.velocity.linear.z, _x.human.velocity.angular.x, _x.human.velocity.angular.y, _x.human.velocity.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.human is None:
        self.human = morse.middleware.ros.humans_msgs.msg.HumanMarker()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 113
      (_x.human.id, _x.human.active, _x.human.pose.position.x, _x.human.pose.position.y, _x.human.pose.position.z, _x.human.pose.orientation.x, _x.human.pose.orientation.y, _x.human.pose.orientation.z, _x.human.pose.orientation.w, _x.human.velocity.linear.x, _x.human.velocity.linear.y, _x.human.velocity.linear.z, _x.human.velocity.angular.x, _x.human.velocity.angular.y, _x.human.velocity.angular.z,) = _get_struct_QB13d().unpack(str[start:end])
      self.human.active = bool(self.human.active)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_QB13d().pack(_x.human.id, _x.human.active, _x.human.pose.position.x, _x.human.pose.position.y, _x.human.pose.position.z, _x.human.pose.orientation.x, _x.human.pose.orientation.y, _x.human.pose.orientation.z, _x.human.pose.orientation.w, _x.human.velocity.linear.x, _x.human.velocity.linear.y, _x.human.velocity.linear.z, _x.human.velocity.angular.x, _x.human.velocity.angular.y, _x.human.velocity.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.human is None:
        self.human = morse.middleware.ros.humans_msgs.msg.HumanMarker()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 113
      (_x.human.id, _x.human.active, _x.human.pose.position.x, _x.human.pose.position.y, _x.human.pose.position.z, _x.human.pose.orientation.x, _x.human.pose.orientation.y, _x.human.pose.orientation.z, _x.human.pose.orientation.w, _x.human.velocity.linear.x, _x.human.velocity.linear.y, _x.human.velocity.linear.z, _x.human.velocity.angular.x, _x.human.velocity.angular.y, _x.human.velocity.angular.z,) = _get_struct_QB13d().unpack(str[start:end])
      self.human.active = bool(self.human.active)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_QB13d = None
def _get_struct_QB13d():
    global _struct_QB13d
    if _struct_QB13d is None:
        _struct_QB13d = struct.Struct("<QB13d")
    return _struct_QB13d
