# CMake generated Testfile for 
# Source directory: /home/ptsingaman/morse/testing/base
# Build directory: /home/ptsingaman/morse/testing/base
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(base/base_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/base_testing.py")
add_test(base/renaming_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/renaming_testing.py")
add_test(base/builder_wheeled_robot "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/builder_wheeled_robot.py")
add_test(base/friction_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/friction_testing.py")
add_test(base/levels "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/levels.py")
add_test(base/accelerometer_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/accelerometer_testing.py")
add_test(base/airspeed_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/airspeed_testing.py")
add_test(base/armature_pose_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/armature_pose_testing.py")
add_test(base/attitude_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/attitude_testing.py")
add_test(base/barometer_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/barometer_testing.py")
add_test(base/battery_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/battery_testing.py")
add_test(base/depth_camera_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/depth_camera_testing.py")
add_test(base/gps_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/gps_testing.py")
add_test(base/gyroscope_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/gyroscope_testing.py")
add_test(base/magnetometer_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/magnetometer_testing.py")
add_test(base/odometry_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/odometry_testing.py")
add_test(base/pose_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/pose_testing.py")
add_test(base/proximity_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/proximity_testing.py")
add_test(base/radar_altimeter_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/radar_altimeter_testing.py")
add_test(base/sick_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/sick_testing.py")
add_test(base/semantic_camera_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/semantic_camera_testing.py")
add_test(base/semantic_camera_tag_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/semantic_camera_tag_testing.py")
add_test(base/semantic_camera_relative_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/semantic_camera_relative_testing.py")
add_test(base/thermometer_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/thermometer_testing.py")
add_test(base/search_and_rescue_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/search_and_rescue_testing.py")
add_test(base/velocity_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/velocity_testing.py")
add_test(base/video_camera_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/video_camera_testing.py")
add_test(base/collision_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/collision_testing.py")
add_test(base/armature_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/armature_testing.py")
add_test(base/external_force_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/external_force_testing.py")
add_test(base/destination_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/destination_testing.py")
add_test(base/drag_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/drag_testing.py")
add_test(base/gripper_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/gripper_testing.py")
add_test(base/light_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/light_testing.py")
add_test(base/orientation_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/orientation_testing.py")
add_test(base/orientation_speed_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/orientation_speed_testing.py")
add_test(base/rotorcraft_waypoint_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/rotorcraft_waypoint_testing.py")
add_test(base/steer_force_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/steer_force_testing.py")
add_test(base/stabilized_quadrirotor_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/stabilized_quadrirotor_testing.py")
add_test(base/teleport_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/teleport_testing.py")
add_test(base/vw_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/vw_testing.py")
add_test(base/waypoint_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/waypoint_testing.py")
add_test(base/xyw_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/xyw_testing.py")
add_test(base/ptu_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/ptu_testing.py")
add_test(base/multiple_ptu_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/multiple_ptu_testing.py")
add_test(base/ned_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/ned_testing.py")
add_test(base/utm_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/utm_testing.py")
add_test(base/ecef_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/ecef_testing.py")
add_test(base/geodetic_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/geodetic_testing.py")
add_test(base/pose_noise_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/pose_noise_testing.py")
add_test(base/imu_noise_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/imu_noise_testing.py")
add_test(base/communication_service_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/communication_service_testing.py")
add_test(base/socket_sync_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/socket_sync_testing.py")
add_test(base/time_scale_testing "/usr/bin/python3" "/home/ptsingaman/morse/testing/base/time_scale_testing.py")
